# Set-up ------------------------------------------------------------------
library(tidyverse)
library(haven)

if (Sys.info()["user"] == "jeremiahcha") {
  setwd("/Users/jeremiahcha/Desktop/github/cces_candidates/")
}


# Data Loading ------------------------------------------------------------

js_06 <- read_dta("data/snyder/2020-06-13 election_results_2006_2016.dta") # Candidate data 2006-2016
js_18 <- read_dta("data/snyder/2020-08-16 election_results_2018_names_updated.dta") # Candidate 2018

js_06_18 <- bind_rows(js_06, js_18) %>% # Binding two datasets
  arrange(state, dist, name)

js_20 <- read_dta("data/snyder/2021-06-19_election_results_2020_pres_house_ussen.dta") %>%
  filter(
    party != "Write-in",
    party != "Write-in (Independent)",
    party != "Write-in (Common Sense Moderate)",
    party != "Write-in (Libertarian)",
    party != "Write-in (Democratic)",
    party != "Write-in (Republican)"
  ) # Candidate data 2020


# New 2020 Candidates -----------------------------------------------------

new <- c(
  "AVERHART, JAMES", "CARL, JERRY", "HARVEY-HALL, PHYLLIS", "MOORE, BARRY",
  "WINFREY, ADIA", "GALVIN, ALYSE S.", "SHEDD, TIFFANY", "MARTIN, BRANDON",
  "BAH, IMAN", "SCHLASS, BRANDON", "WOOD, DANIEL", "DISANTO, DELINA",
  "BARNETT, JOSHUA", "MUSCATO, MICHAEL", "WILLIAMS, CELESTE", "HANSON, WILLIAM H.",
  "HAMILTON, TAMIKA", "KENNEDY, BRYNNE S.", "GIBLIN, SCOTT", "BISH, CHRIS",
  "PATTERSON, BUZZ", "BUBSER, CHRISTINE", "OBERNOLTE, JAY", "HOWZE, TED",
  "SHARMA, NISHA", "BUTTAR, SHAHID", "PITERMAN, NIKKA", "PETEL, RAN S.",
  "HAYDEN, ALISON", "COOKINGHAM, KEVIN", "TANDON, RITESH", "KUMAR, RISHI",
  "VALADAO, DAVID G.", "MANGONE, KIM", "CALDWELL, ANDY", "SMITH, CHRISTY",
  "GARCIA, MIKE", "BALDWIN-KENNEDY, RONDA", "EARLY, ERIC", "GIBBONEY, AGNES",
  "BRADLEY, JAMES P.", "KIM, DAVID", "CARGILE, MIKE", "CRUZ, ERIN",
  "WEBBER, ERROL", "TOLAR, MICHAEL", "O'MARA, WILLIAM (LIAM)", "COLLINS, JOE E., III",
  "JOYA, ANALILIA", "RATHS, GREG", "WATERS, JAMES S.", "STEEL, MICHELLE",
  "MARYOTT, BRIAN", "DEBELLO, JIM", "JACOBS, SARA", "GOMEZ, GEORGETTE",
  "BOLLING, SHANE", "FUREY, KYLE", "KOK, JAN", "WINN, CHARLIE", "ATKINSON, THOM",
  "SWING, GARY", "BOEBERT, LAUREN", "KEIL, JOHN RYAN", "MILTON, CRITTER",
  "MCCORKLE, IKE", "IRELAND, LAURA", "FREELAND, JILLIAN", "DUFFETT, ED",
  "MURPHY, MARCUS ALLEN", "KELTIE, REBECCA", "HOUSE, STEVE", "KULIKOWSKI, JAIMIE LYNN",
  "BILES, KEN", "OLSZTA, DAVID", "FAY, MARY", "ANDERSON, JUSTIN", "MARTINEAU, CASSANDRA",
  "STREICKER, MARGARET", "PAGLINO, JUSTIN C.", "RIDDLE, JONATHAN", "MERLEN, BRIAN",
  "SULLIVAN, DAVID X.", "WALCZAK, BRUCE W.", "MURPHY, LEE", "PURCELL, CATHERINE S.",
  "ROGERS, DAVID L.", "EHR, PHIL", "ORAM, ALBERT", "CHRISTENSEN, ADAM", "CAMMACK, KAT",
  "DEEGAN, DONNA", "ADLER, GARY", "VALENTIN, LEO", "GARLINGTON, WILLIAM R.",
  "KENNEDY, JIM", "OLSON, WILLIAM P. (BILL)", "FRANCOIS, VENNIA", "WALKER, KIMBERLY",
  "LUNA, ANNA PAULINA", "FRANKLIN, SCOTT", "GOOD, MARGARET",
  "MURRAY, THEODORE (PINK TIE)", "KEITH, PAM", "MILLER, K W.",
  "BANYAI, CINDY LYN", "DONALDS, BYRON", "MUSSELWHITE, GREG",
  "LOOMER, LAURA", "MALKEMUS, CHARLESTON", "PRUDEN, JAMES (JIM)",
  "SPICER, LAVERN", "OLIVO, CHRISTINE ALEXANDRIA", "GIMENEZ, CARLOS",
  "GRIGGS, JOYCE MARIE", "COLE, DON", "ALMONORD, VAL",
  "EZAMMUDEEN, JOHSIE CRUZ", "WILLIAMS, NIKEMA", "STANTON-KING, ANGELA",
  "MCCORMICK, RICH", "HOLLIDAY, LINDSAY", "PANDY, DEVIN", "CLYDE, ANDREW",
  "BARRETT, DANA", "JOHNSON, LIZ", "HITES, BECKY E.", "AUSDAL, KEVIN VAN",
  "GREENE, MARJORIE TAYLOR", "AHELE, KAIALIAI (KAI)", "AKANA, JOE",
  "HOOMANAWANUI, JONATHAN", "BURRUS, RON", "SOTO, RUDY", "EVANS, JOE",
  "LAW, IDAHO SIERRA", "WHITE, PHILANISE", "RABORN, THERESA J.",
  "NEWMAN, MARIE", "FRICILONE, MIKE", "SOLORIO, JESUS",
  "WILDA, THOMAS J.", "IVES, JEANNE", "REDPATH, BILL",
  "JENNINGS, TRACY", "NELSON, PRESTON GABRIEL", "SANGARI, SARGIS",
  "MUKHERJEE, VALERIE RAMIREZ", "LAIB, RICK", "LENZI, RAYMOND C.",
  "WEAVER, ERIKA C.", "MILLER, MARY", "BRZOZOWSKI, DANI",
  "KING, ESTHER JOY", "PETRILLI, GEORGE", "MRVAN, FRANK J.",
  "STRAUSS, MICHAEL", "HACKETT, PATRICIA (PAT)", "COLDIRON, CHIP",
  "MACKEY, JOE", "HALE, CHRISTINA", "SPARTZ, VICTORIA",
  "TUCKER, KENNETH", "SMITH, SUSAN MARIE", "MARSILI, E THOMASINA",
  "RODENBERGER, JAMES D.", "RUFF, ANDY", "MILLIS, TONYA L.",
  "FINKENAUER, ABBY", "HINSON, ASHLEY", "HART, RITA R.",
  "FEENSTRA, RANDY", "BARNETT, KALI", "MANN, TRACEY",
  "DE LA ISLA, MICHELLE", "ADKINS, AMANDA L.", "LOMBARD, LAURA",
  "RHODES, JAMES", "PERRY, ROBERT LEE", "CARTER, LEWIS", "OWENSBY, ALEXANDRA",
  "BEST, MATTHEW RYAN", "HICKS, JOSH", "HARRIS, GLENN ADRAIN",
  "SCHILLING, DAVID M.", "VINCENT, SHELDON C., SR.", "JAMES, COLBY",
  "HARRIS, BRAYLON", "LELEUX, BRANDON", "HOUSTON, KENNY", "GIBSON, BEN",
  "CHRISTOPHE, SANDRA (CANDY)", "LEMELLE, MARTIN, JR.", "SNOWDEN, PHILLIP",
  "LAGARDE, JESSE P.", "LETLOW, LUKE J.", "HARRIS, LANCE", "ROBINSON, (SCOTTY)",
  "GUILLORY, ALLEN, SR.", "HASTY, (MATT)", "WILLIAMS, DARTANYON (DAW)",
  "SLOAN, SHANNON", "TORREGANO, RICHARD (RPT)", "ALLEN, JAY T.",
  "CRAFTS, DALE JOHN", "MASON, MIA", "SALLING, JOHNNY RAY", "PALOMBI, CHRIS",
  "PARROTT, NEIL C.", "HERRICK, JASON", "MFUME, KWEISI", "KLACIK, KIMBERLY",
  "COLL, GREGORY THOMAS", "AUCHINCLOSS, JAKE", "HALL, JULIE A.",
  "COLARUSSO, CAROLINE", "MORAN, JOHN PAUL", "OWENS, ROY A., SR.",
  "LOTT, JONATHAN D.", "MANLEY, MICHAEL", "BOREN, BEN", "BERGHOEF, BRYAN",
  "RIEKSE, MAX", "CREVIERE, JEAN-MICHEL", "MEIJER, PETER", "CANNY, DAVID",
  "SLEPR, AMY", "KELLY, TIM", "HARRIS, JAMES", "HOADLEY, JON",
  "DEPOY, JEFF", "JUNGE, PAUL", "HARTMAN, JOE", "LANGWORTHY, CHARLES J.",
  "SALIBA, MIKE", "MCCLAIN, LISA", "ESSHAKI, ERIC S.", "DUDENHOEFER, DAVID",
  "BOMER, ARTICIA", "PATRICK, ROBERT VANCE", "ROOD, BILL", "KISTNER, TYLER",
  "WEEKS, ADAM CHARLES", "QUALLS, KENDALL", "RECHTZIGEL, GENE",
  "JOHNSON, LACY", "MOORE, MICHAEL", "ZAHRADKA, TAWNJA", "FISCHBACH, MICHELLE",
  "JOHNSON, SLATER", "ANDERSON, RAE HART", "NYSTROM, QUINN", "ELIASON, ANTONIA",
  "FLOWERS, BRIAN", "BENFORD, DOROTHY (DOT)", "BUSH, CORI", "ROGERS, ANTHONY",
  "FURMAN, ALEX", "SCHUPP, JILL", "SCHULTE, MARTIN", "REZABEK, MEGAN",
  "STEINMAN, LEONARD J., II", "SIMMONS, LINDSEY", "KOONSE, STEVEN K.",
  "DERKS, RYAN", "DOMINICK, ROBIN", "ROSS, GENA L.", "MONTSENY, TERESA",
  "SCHMITZ, TOM", "BOLZ, KATE", "GRACE, DENNIS B.", " SCHAEFFER, TYLER",
  "ELSWORTH, MARK, JR.", "HOBBS, DUSTIN C.", "ACKERMAN, PATRICIA",
  "RODIMER, DAN (BIG DAN)", "RIDGES, ED S., II", "MARCHANT, JIM",
  "ESTEBAN, JONATHAN ROYCE", "RUBINSON, BARRY L.", "MOWERS, MATT",
  "DUMONT, ZACHARY S.", "NEGRON, STEVEN", "OLDING, ANDREW",
  "GUSTAFSON, CLAIRE H.", "KENNEDY, AMY", "HARVEY, JENNA",
  "EHRNSTROM, JESSE", "RICHTER, DAVID", "WEBER, MARTIN",
  "SCHMID, STEPHANIE", "PACHUTA, ANDREW", "PALLOTTA, FRANK T.",
  "VELLUCCI, LOUIS A.", "ONUOHA, CHRISTIAN", "MUSHNICK, JASON TODD",
  "PREMPEH, BILLY", "AURIEMMA, CHRIS", "ZINONE, JENNIFER",
  "KHALFANI, AKIL", "FITCHETTE, KHALIAH", "MIRRIONE, JOHN",
  "BECCHI, ROSEMARY", "RAZZOLI, MARK", "SMITH, SANDY", "SWAIN, ALAN D.",
  "FARROW, DARYL", "MURPHY, GREGORY F.", "THOMAS, ROBERT", "HAYWOOD, LEE",
  "WARD, CHRISTOPHER M.", "TIMMONS-GOODSON, PATRICIA", "WALLACE, CYNTHIA L.",
  "BISHOP, DAN", "PARKER, DAVID", "DAVIS, MOE", "CAWTHORN, MADISON",
  "DEBRUHL, TRACEY", "ZWINAK, TAMARA", "HUFFMAN, SCOTT",
  "HOLMES, MICHELLE GARCIA", "FERNANDEZ, TERESA LEGER", "JOHNSON, ALEXIS M.",
  "GOROFF, NANCY S.", "GORDON, JACKIE", "GARBARINO, ANDREW R.",
  "BURGER, HARRY R.", "SANTOS, GEORGE A.", "RABIN, HOWARD",
  "TUMAN, DOUGLAS L.", "NAHAM, JOSEPH R.", "ZMICH, THOMAS J.",
  "KELLY, BRIAN W.", "MIDONNET, GILBERT", "WALLACE, GARFIELD H.",
  "JEAN-PIERRE, CONSTANTINE", "POPKIN, GARY", "BERNSTEIN, CATHY A.",
  "MADRID, MICHAEL", "MALLIOTAKIS, NICOLE", "SANTIAGO-CANO, CARLOS",
  "KOLLN, STEVEN", "MORRIS-PERRY, CHRISTOPHER", "CUMMINGS, JOHN C.",
  "CARUSO-CABRERA, MICHELLE", "TORRES, RITCHIE", "DELICES, PATRICK",
  "BOWMAN, JAMAAL", "MCMANUS, PATRICK", "JONES, MONDAIRE",
  "MCARDLE-SCHULMAN, MAUREEN", "GOTTESFELD, YEHUDIS",
  "EISEN, JOSHUA", "PARIETTI, MICHAEL I.", "VAN DE WATER, KYLE",
  "ALEXANDER, VICTORIA N.", "JOY, ELIZABETH L.", "PRICE, KEITH D., JR.",
  "KOLSTEE, ANDREW M.", "WILLIAMS, STEVEN", "MITRIS, GEORGE",
  "DONOVAN, RICKY T., SR.", "RALEIGH, MICHAEL P.", "MCMURRAY, NATHAN D.",
  "JACOBS, CHRIS", "WHITMER, DUANE J.", "RAKNERUD, ZACH",
  "ARMSTRONG, KELLY", "PETERSON, STEVEN JAMES", "LAW, IDAHO SIERRA"
)

# Regex Check -------------------------------------------------------------

js_06_18 %>%
  filter(str_detect(name, "CARBAJAL,")) %>%
  select(name, state, dist, office, year)

js_20 %>%
  filter(str_detect(name, "CARBAJAL")) %>%
  select(name, state, dist, office, year)


# 2020 Name Changes -------------------------------------------------------
# use Stata

# New York Aggregation ----------------------------------------------------
# use Stata